# Analisis exploratorio datos de Properati

Datos provistos por <a href='http://www.properati.com.ar'>Properati</a>

### Analisis de datos

In [4]:
# magic function para hacer que los graficos de matplotlib se renderizen en el notebook.
%matplotlib inline

import datetime as datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('default') # haciendo los graficos un poco mas bonitos xD
plt.rcParams['figure.figsize'] = (15, 5)

In [5]:
propiedades = pd.read_csv('./datos/properati-AR-2014-01-01-properties-sell.csv', low_memory=False)

In [6]:
propiedades = propiedades[propiedades['place_with_parent_names'].str.contains('G.B.A|Capital Federal')]

In [7]:
propiedades.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51384 entries, 0 to 67747
Data columns (total 20 columns):
created_on                    51384 non-null object
operation                     51384 non-null object
property_type                 51384 non-null object
place_name                    51384 non-null object
place_with_parent_names       51384 non-null object
geonames_id                   42331 non-null float64
lat-lon                       48136 non-null object
lat                           48136 non-null float64
lon                           48133 non-null float64
price                         44054 non-null float64
currency                      44054 non-null object
price_aprox_local_currency    44054 non-null float64
price_aprox_usd               44054 non-null float64
surface_in_m2                 43989 non-null float64
price_usd_per_m2              38672 non-null float64
floor                         8209 non-null float64
rooms                         41243 non-null float64
expenses                      2352 non-null object
properati_url                 51384 non-null object
image_thumbnail               48400 non-null object
dtypes: float64(10), object(10)
memory usage: 8.2+ MB

In [8]:
propiedades.describe()

,geonames_id,lat,lon,price,price_aprox_local_currency,price_aprox_usd,surface_in_m2,price_usd_per_m2,floor,rooms
count,4.233100e+04,48136.000000,48133.000000,4.405400e+04,4.405400e+04,4.405400e+04,43989.000000,38672.000000,8209.000000,41243.000000
mean,3.471893e+06,-34.402908,-58.560748,3.077193e+05,1.237571e+06,1.926631e+05,136.214690,2090.954741,15.194543,2.467037
std,3.505344e+05,3.293609,2.877027,3.997415e+05,1.428396e+06,2.223704e+05,275.123846,1572.511667,105.428147,1.309727
min,3.427208e+06,-58.804368,-122.485251,5.300000e+03,3.404455e+04,5.300000e+03,20.000000,0.003367,0.000000,0.000000
25%,3.429617e+06,-34.634124,-58.564897,9.500000e+04,5.652680e+05,8.800000e+04,47.000000,1351.851852,2.000000,1.000000
50%,3.432039e+06,-34.597840,-58.473816,1.570000e+05,8.350550e+05,1.300000e+05,73.000000,1910.427145,4.000000,2.000000
75%,3.434130e+06,-34.557156,-58.414576,3.600000e+05,1.393975e+06,2.170117e+05,145.000000,2516.129032,7.000000,3.000000
max,6.693230e+06,47.995192,62.203742,1.111111e+07,7.137222e+07,1.111111e+07,9767.000000,56500.000000,5055.000000,39.000000

In [9]:
propiedades.head(5)

,created_on,operation,property_type,place_name,place_with_parent_names,geonames_id,lat-lon,lat,lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_in_m2,price_usd_per_m2,floor,rooms,expenses,properati_url,image_thumbnail
0,2012-08-08,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,3436077.0,"-34.561208,-58.464514",-34.561208,-58.464514,NaN,NaN,NaN,NaN,102.0,NaN,10.0,3.0,850 aprox,http://www.properati.com.ar/ag_venta_departame...,http://cf-thumbs.properati.com.ar/Cry7pVKa41t_...
1,2012-08-08,sell,apartment,Villa Ballester,|Argentina|Bs.As. G.B.A. Zona Norte|General Sa...,3427467.0,"-34.54673,-58.550579",-34.546730,-58.550579,NaN,NaN,NaN,NaN,73.0,NaN,11.0,3.0,NaN,http://www.properati.com.ar/ah_venta_departame...,http://cf-thumbs.properati.com.ar/MwrzW_dkQbqR...
2,2012-08-08,sell,house,Villa Ballester,|Argentina|Bs.As. G.B.A. Zona Norte|General Sa...,3427467.0,"-34.543776,-58.559615",-34.543776,-58.559615,NaN,NaN,NaN,NaN,485.0,NaN,NaN,4.0,NaN,http://www.properati.com.ar/aj_venta_casa_vill...,http://cf-thumbs.properati.com.ar/2wMqxAsh1N2t...
3,2012-08-08,sell,house,Villa Ballester,|Argentina|Bs.As. G.B.A. Zona Norte|General Sa...,3427467.0,NaN,NaN,NaN,110000.0,USD,706585.0,110000.0,349.0,315.186246,NaN,4.0,NaN,http://www.properati.com.ar/ak_venta_casa_vill...,http://cf-thumbs.properati.com.ar/uMwzJsvexa1C...
4,2012-08-08,sell,apartment,General San Martín,|Argentina|Bs.As. G.B.A. Zona Norte|General Sa...,3433778.0,"-34.622794,-58.577988",-34.622794,-58.577988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,http://www.properati.com.ar/ao_venta_departame...,http://cf-thumbs.properati.com.ar/4kPnofvgR6hs...

### ¿Cuales son los barrios que tienen las propiedades mas caras a la venta por metro cuadrado?

In [10]:
propiedades.groupby(['place_with_parent_names']).mean().sort_values(['price_usd_per_m2'],ascending=False).head(5)

,geonames_id,lat,lon,price,price_aprox_local_currency,price_aprox_usd,surface_in_m2,price_usd_per_m2,floor,rooms
place_with_parent_names,,,,,,,,,,
|Argentina|Capital Federal|Puerto Madero|,3429760.0,-34.612313,-58.363245,715298.863636,4.186055e+06,651678.269148,139.242991,4893.387687,14.785714,2.704036
|Argentina|Capital Federal|Las Cañitas|,NaN,-31.987083,-59.929430,278911.123932,1.657016e+06,257961.555726,91.394231,3325.399109,7.225000,2.452756
|Argentina|Capital Federal|Palermo|Palermo Hollywood|,NaN,-34.582149,-58.433319,307178.547529,1.167414e+06,181741.110532,64.742574,3109.620634,5.705882,1.907937
|Argentina|Capital Federal|Palermo|Palermo Soho|,3430234.0,-34.428270,-58.662968,276905.309859,1.239507e+06,192964.478545,67.830275,3081.736030,4.193548,1.886139
|Argentina|Capital Federal|Recoleta|,3429595.0,-34.497085,-58.253921,426521.165060,2.502605e+06,389601.522976,139.389151,3059.490192,4.877358,3.597156

### ¿Cuales son los barrios donde se venden mas propiedades?

In [12]:
propiedades.groupby('place_with_parent_names').size().sort_values(ascending=False).head(10)

place_with_parent_names
|Argentina|Capital Federal|                                    4281
|Argentina|Capital Federal|Belgrano|                           2131
|Argentina|Bs.As. G.B.A. Zona Norte|Pilar|                     1813
|Argentina|Capital Federal|Palermo|Palermo Chico|              1624
|Argentina|Bs.As. G.B.A. Zona Norte|Tigre|                     1549
|Argentina|Capital Federal|Barrio Norte|                       1245
|Argentina|Capital Federal|Villa Urquiza|                      1228
|Argentina|Capital Federal|Caballito|                          1200
|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza|Ramos Mejía|    1120
|Argentina|Capital Federal|Flores|                             1046
dtype: int64

### ¿Cuales son los barrios donde se venden mas casas?

In [13]:
propiedades[propiedades["property_type"]=="house"].groupby('place_with_parent_names').size().sort_values(ascending=False).head(10)

place_with_parent_names
|Argentina|Bs.As. G.B.A. Zona Norte|Pilar|                     1208
|Argentina|Capital Federal|                                     800
|Argentina|Bs.As. G.B.A. Zona Norte|Tigre|                      751
|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|                     509
|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|Ituzaingó|        499
|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|Castelar|             321
|Argentina|Bs.As. G.B.A. Zona Norte|General San Martín|         288
|Argentina|Bs.As. G.B.A. Zona Sur|La Plata|                     272
|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza|Ramos Mejía|     267
|Argentina|Bs.As. G.B.A. Zona Norte|Vicente López|Olivos|       239
dtype: int64